In [6]:
import pandas as pd
import numpy as np

data = pd.read_csv('examples/2015.csv')
data.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [7]:
data.groupby('Region')['Happiness Score'].mean()

Region
Australia and New Zealand          7.285000
Central and Eastern Europe         5.332931
Eastern Asia                       5.626167
Latin America and Caribbean        6.144682
Middle East and Northern Africa    5.406900
North America                      7.273000
Southeastern Asia                  5.317444
Southern Asia                      4.580857
Sub-Saharan Africa                 4.202800
Western Europe                     6.689619
Name: Happiness Score, dtype: float64

In [9]:
data.groupby('Region').agg({'Happiness Score': 'mean',
                            'Economy (GDP per Capita)': ['min', 'max']})

                                Happiness Score Economy (GDP per Capita)  \
                                           mean                      min
Region
Australia and New Zealand              7.285000                  1.25018
Central and Eastern Europe             5.332931                  0.39047
Eastern Asia                           5.626167                  0.82819
Latin America and Caribbean            6.144682                  0.26673
Middle East and Northern Africa        5.406900                  0.54649
North America                          7.273000                  1.32629
Southeastern Asia                      5.317444                  0.27108
Southern Asia                          4.580857                  0.31982
Sub-Saharan Africa                     4.202800                  0.00000
Western Europe                         6.689619                  1.15406


                                     max
Region
Australia and New Zealand        1.33358
Central and Eastern Europe       1.18498
Eastern Asia                     1.38604
Latin America and Caribbean      1.21183
Middle East and Northern Africa  1.69042
North America                    1.39451
Southeastern Asia                1.52186
Southern Asia                    0.83524
Sub-Saharan Africa               1.06024
Western Europe                   1.56391

In [12]:
z_score_fn = lambda x: (x - x.mean()) / x.std()
data['Regional_Happiness_ZScore'] = data.groupby('Region')['Happiness Score'].transform(z_score_fn)
data.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Regional_Happiness_ZScore
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,1.088286
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,1.056755
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,1.015522
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,1.009458
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,0.707107

In [20]:
df_scores = data[['Country', 'Happiness Score']].head(5)
df_regions = data[['Country', 'Region']].iloc[2:7]
inner = pd.merge(df_scores, df_regions, how='inner')
outer = pd.merge(df_scores, df_regions, how='outer')
right = pd.merge(df_scores, df_regions, how='right')
left = pd.merge(df_scores, df_regions, how='left')
display(outer)

       Country  Happiness Score          Region
0       Canada            7.427   North America
1      Denmark            7.527  Western Europe
2      Finland              NaN  Western Europe
3      Iceland            7.561             NaN
4  Netherlands              NaN  Western Europe
5       Norway            7.522  Western Europe
6  Switzerland            7.587             NaN

In [26]:
top_3 = data.head(3)
bottom_3 = data.tail(3)
vertical = pd.concat([top_3, bottom_3])

country = data[['Country']].head()
Zscore = data[['Regional_Happiness_ZScore']].head()
horizontal = pd.concat([country, Zscore], axis=1)

display(horizontal)
display(vertical)

       Country  Regional_Happiness_ZScore
0  Switzerland                   1.088286
1      Iceland                   1.056755
2      Denmark                   1.015522
3       Norway                   1.009458
4       Canada                   0.707107

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Regional_Happiness_ZScore
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,1.088286
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,1.056755
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,1.015522
155,Syria,Middle East and Northern Africa,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858,-2.179898
156,Burundi,Sub-Saharan Africa,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302,-2.129087
157,Togo,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726,-2.237362