In [ ]:
import pandas as pd

data = pd.read_csv('example/train_and_test2.csv')
data.head()
data.tail()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
1304,1305,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1306,1307,38.5,7.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1307,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1308,1309,28.0,22.3583,0,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

In [15]:
data.describe()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
count,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.0,1309.0,1309.0,1309.0,1309.0,...,1309.0,1309.0,1309.0,1309.000000,1309.0,1309.0,1307.000000,1309.0,1309.0,1309.000000
mean,655.000000,29.503186,33.281086,0.355997,0.498854,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.294882,0.0,0.0,1.492731,0.0,0.0,0.261268
std,378.020061,12.905241,51.741500,0.478997,1.041658,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.837836,0.0,0.0,0.814626,0.0,0.0,0.439494
min,1.000000,0.170000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.000000,0.0,0.0,0.000000,0.0,0.0,0.000000
25%,328.000000,22.000000,7.895800,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.000000,0.0,0.0,1.000000,0.0,0.0,0.000000
50%,655.000000,28.000000,14.454200,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,0.000000
75%,982.000000,35.000000,31.275000,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,1.000000
max,1309.000000,80.000000,512.329200,1.000000,8.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,1.000000

In [18]:
print(f"Rows and Columns: {data.shape}")
data.dtypes

Rows and Columns: (1309, 28)

Passengerid      int64
Age            float64
Fare           float64
Sex              int64
sibsp            int64
zero             int64
zero.1           int64
zero.2           int64
zero.3           int64
zero.4           int64
zero.5           int64
zero.6           int64
Parch            int64
zero.7           int64
zero.8           int64
zero.9           int64
zero.10          int64
zero.11          int64
zero.12          int64
zero.13          int64
zero.14          int64
Pclass           int64
zero.15          int64
zero.16          int64
Embarked       float64
zero.17          int64
zero.18          int64
2urvived         int64
dtype: object

In [20]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Passengerid  1309 non-null   int64
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64
 4   sibsp        1309 non-null   int64
 5   zero         1309 non-null   int64
 6   zero.1       1309 non-null   int64
 7   zero.2       1309 non-null   int64
 8   zero.3       1309 non-null   int64
 9   zero.4       1309 non-null   int64
 10  zero.5       1309 non-null   int64
 11  zero.6       1309 non-null   int64
 12  Parch        1309 non-null   int64
 13  zero.7       1309 non-null   int64
 14  zero.8       1309 non-null   int64
 15  zero.9       1309 non-null   int64
 16  zero.10      1309 non-null   int64
 17  zero.11      1309 non-null   int64
 18  zero.12      1309 non-null   int64
 19  zero.13      1309 non-null   int64
 20  zero.14      1309 non-null   int64
 21  Pclass       1309 non-null   int64
 22  zero.15      1309 non-null   int64
 23  zero.16      1309 non-null   int64
 24  Embarked     1307 non-null   float64
 25  zero.17      1309 non-null   int64
 26  zero.18      1309 non-null   int64
 27  2urvived     1309 non-null   int64
dtypes: float64(3), int64(25)
memory usage: 286.5 KB

In [ ]:
# [Rows, Columns]
data.iloc[0]
data.iloc[-1]
data.iloc[:,:2]
data.iloc[100:105]
data.iloc[0:5, 0:5]   # First 5 rows

   Passengerid   Age     Fare  Sex  sibsp
0            1  22.0   7.2500    0      1
1            2  38.0  71.2833    1      1
2            3  26.0   7.9250    1      0
3            4  35.0  53.1000    1      1
4            5  35.0   8.0500    0      0

In [35]:
data.loc[0:5, 'Age']  # First 6 rows
data.loc[:, ['Age', 'Sex', 'Fare']]
data.loc[0, 'Fare']
data.loc[10:20, 'Fare': 'Parch']
data.loc[data['Age'] > 50]

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
6,7,54.0,51.8625,0,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
11,12,58.0,26.5500,1,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
15,16,55.0,16.0000,1,0,0,0,0,0,0,...,0,0,0,2,0,0,2.0,0,0,1
33,34,66.0,10.5000,0,0,0,0,0,0,0,...,0,0,0,2,0,0,2.0,0,0,0
54,55,65.0,61.9792,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1247,1248,59.0,51.4792,1,2,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
1265,1266,54.0,81.8583,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
1269,1270,55.0,50.0000,0,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
1278,1279,57.0,13.0000,0,0,0,0,0,0,0,...,0,0,0,2,0,0,2.0,0,0,0
1282,1283,51.0,39.4000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0

In [62]:
data[(data['Age'] > 30) & (data['Fare'] > 100)]
min_age = 30
expensive_fare = 100
data.query('Age > @min_age and Fare > @expensive_fare')

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
195,196,58.0,146.5208,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
215,216,31.0,113.2750,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
258,259,35.0,512.3292,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
268,269,58.0,153.4625,1,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
269,270,35.0,135.6333,1,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
299,300,50.0,247.5208,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
318,319,31.0,164.8667,1,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
319,320,40.0,134.5000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
325,326,36.0,135.6333,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
332,333,38.0,153.4625,0,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
337,338,41.0,134.5000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
380,381,42.0,227.5250,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
390,391,36.0,120.0000,0,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
438,439,64.0,263.0000,0,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
544,545,50.0,106.4250,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
581,582,39.0,110.8833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
609,610,40.0,153.4625,1,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
659,660,58.0,113.2750,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
660,661,50.0,133.6500,0,2,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
679,680,36.0,512.3292,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
698,699,49.0,110.8833,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
716,717,38.0,227.5250,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
737,738,35.0,512.3292,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
763,764,36.0,120.0000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
779,780,43.0,211.3375,1,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
856,857,45.0,164.8667,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
915,916,48.0,262.3750,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
950,951,36.0,262.3750,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
960,961,60.0,263.0000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
965,966,35.0,211.5000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
966,967,32.5,211.5000,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
972,973,67.0,221.7792,0,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
1005,1006,63.0,221.7792,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
1032,1033,33.0,151.5500,1,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
1033,1034,61.0,262.3750,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1093,1094,47.0,227.5250,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1108,1109,57.0,164.8667,0,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
1109,1110,50.0,211.5000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1130,1131,48.0,106.4250,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1133,1134,45.0,134.5000,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1205,1206,55.0,135.6333,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1207,1208,57.0,146.5208,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1215,1216,39.0,211.3375,1,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
1234,1235,58.0,512.3292,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1262,1263,31.0,134.5000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1266,1267,45.0,262.3750,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1298,1299,50.0,211.5000,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0

In [67]:
import numpy as np

data.loc[0:10, 'Pclass'] = np.nan
data.isnull().sum()

Passengerid     0
Age            11
Fare            0
Sex             0
sibsp           0
zero            0
zero.1          0
zero.2          0
zero.3          0
zero.4          0
zero.5          0
zero.6          0
Parch           0
zero.7          0
zero.8          0
zero.9          0
zero.10         0
zero.11         0
zero.12         0
zero.13         0
zero.14         0
Pclass         11
zero.15         0
zero.16         0
Embarked        0
zero.17         0
zero.18         0
2urvived        0
dtype: int64

In [69]:
data['Age'] = data['Age'].fillna(0)
data = data.dropna(subset=['Pclass', 'Embarked'])
data.isnull().sum()

Passengerid    0
Age            0
Fare           0
Sex            0
sibsp          0
zero           0
zero.1         0
zero.2         0
zero.3         0
zero.4         0
zero.5         0
zero.6         0
Parch          0
zero.7         0
zero.8         0
zero.9         0
zero.10        0
zero.11        0
zero.12        0
zero.13        0
zero.14        0
Pclass         0
zero.15        0
zero.16        0
Embarked       0
zero.17        0
zero.18        0
2urvived       0
dtype: int64

In [72]:
data_sorted_id = data.sort_values(by='Passengerid')
data_sorted_id.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
11,12,58.0,26.5500,1,0,0,0,0,0,0,...,0,0,0,1.0,0,0,2.0,0,0,1
12,13,20.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3.0,0,0,2.0,0,0,0
13,14,39.0,31.2750,0,1,0,0,0,0,0,...,0,0,0,3.0,0,0,2.0,0,0,0
14,15,14.0,7.8542,1,0,0,0,0,0,0,...,0,0,0,3.0,0,0,2.0,0,0,0
15,16,55.0,16.0000,1,0,0,0,0,0,0,...,0,0,0,2.0,0,0,2.0,0,0,1

In [75]:
data_sorted_fare = data.sort_values(by='Fare', ascending=False)
data_sorted_fare.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
1234,1235,58.0,512.3292,1,0,0,0,0,0,0,...,0,0,0,1.0,0,0,0.0,0,0,0
679,680,36.0,512.3292,0,0,0,0,0,0,0,...,0,0,0,1.0,0,0,0.0,0,0,1
737,738,35.0,512.3292,0,0,0,0,0,0,0,...,0,0,0,1.0,0,0,0.0,0,0,1
258,259,35.0,512.3292,1,0,0,0,0,0,0,...,0,0,0,1.0,0,0,0.0,0,0,1
960,961,60.0,263.0000,1,1,0,0,0,0,0,...,0,0,0,1.0,0,0,2.0,0,0,0

In [79]:
data_multi_sort = data.sort_values(by=['Age', 'Fare'])
data_multi_sort.head(10)

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
1245,1246,0.17,20.5750,1,1,0,0,0,0,0,...,0,0,0,3.0,0,0,2.0,0,0,0
1092,1093,0.33,14.4000,0,0,0,0,0,0,0,...,0,0,0,3.0,0,0,2.0,0,0,0
803,804,0.42,8.5167,0,0,0,0,0,0,0,...,0,0,0,3.0,0,0,0.0,0,0,1
755,756,0.67,14.5000,0,1,0,0,0,0,0,...,0,0,0,2.0,0,0,2.0,0,0,1
1172,1173,0.75,13.7750,0,1,0,0,0,0,0,...,0,0,0,3.0,0,0,2.0,0,0,0
469,470,0.75,19.2583,1,2,0,0,0,0,0,...,0,0,0,3.0,0,0,0.0,0,0,1
644,645,0.75,19.2583,1,2,0,0,0,0,0,...,0,0,0,3.0,0,0,0.0,0,0,1
1198,1199,0.83,9.3500,0,0,0,0,0,0,0,...,0,0,0,3.0,0,0,2.0,0,0,0
831,832,0.83,18.7500,0,1,0,0,0,0,0,...,0,0,0,2.0,0,0,2.0,0,0,1
78,79,0.83,29.0000,0,0,0,0,0,0,0,...,0,0,0,2.0,0,0,2.0,0,0,1

In [81]:
data['Fare_Double'] = data['Fare'] * 2
data['FamilySize'] = data['sibsp'] + 1
data.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived,Fare_Double,FamilySize
11,12,58.0,26.5500,1,0,0,0,0,0,0,...,0,1.0,0,0,2.0,0,0,1,53.1000,1
12,13,20.0,8.0500,0,0,0,0,0,0,0,...,0,3.0,0,0,2.0,0,0,0,16.1000,1
13,14,39.0,31.2750,0,1,0,0,0,0,0,...,0,3.0,0,0,2.0,0,0,0,62.5500,2
14,15,14.0,7.8542,1,0,0,0,0,0,0,...,0,3.0,0,0,2.0,0,0,0,15.7084,1
15,16,55.0,16.0000,1,0,0,0,0,0,0,...,0,2.0,0,0,2.0,0,0,1,32.0000,1

In [84]:
data = data.rename(columns={
    'sibsp': 'Siblings_Spouses',
    'Sex': 'Gender',
    '2urvived': 'Survived'
})
data.head()

,Passengerid,Age,Fare,Gender,Siblings_Spouses,zero,zero.1,zero.2,zero.3,zero.4,...,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,Survived,Fare_Double,FamilySize
11,12,58.0,26.5500,1,0,0,0,0,0,0,...,0,1.0,0,0,2.0,0,0,1,53.1000,1
12,13,20.0,8.0500,0,0,0,0,0,0,0,...,0,3.0,0,0,2.0,0,0,0,16.1000,1
13,14,39.0,31.2750,0,1,0,0,0,0,0,...,0,3.0,0,0,2.0,0,0,0,62.5500,2
14,15,14.0,7.8542,1,0,0,0,0,0,0,...,0,3.0,0,0,2.0,0,0,0,15.7084,1
15,16,55.0,16.0000,1,0,0,0,0,0,0,...,0,2.0,0,0,2.0,0,0,1,32.0000,1

In [92]:
data = data.drop(columns=['Fare_Double'])
data.columns

Index(['Passengerid', 'Age', 'Fare', 'Gender', 'Siblings_Spouses', 'zero.1',
       'zero.2', 'zero.3', 'zero.4', 'zero.5', 'zero.6', 'Parch', 'zero.9',
       'zero.10', 'zero.11', 'zero.12', 'zero.13', 'zero.14', 'Pclass',
       'zero.15', 'zero.16', 'Embarked', 'zero.17', 'zero.18', 'Survived',
       'FamilySize'],
      dtype='str')